PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?term ?label
WHERE {
  { ?s1 ?p1 ?term . 
  }
  UNION
  { ?term ?p2 ?o2 . 
  ?term rdfs:label ?label .
  }
  FILTER(isIRI(?term) && regex(str(?term), "ZP_"))
}