PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?term ?label
WHERE {
  ?term a owl:Class .
  OPTIONAL { ?term rdfs:label ?label }
  FILTER(STRSTARTS(STR(?term), "http://purl.obolibrary.org/obo/ZP_"))
}
